In [ ]:
 import numpy as np
 a = np.array([1, 2, 3]) #create a rank 1 array
 print(type(a))
 print(a.shape)
 print(a[0], a[1], a[2])
a[0] = 5
print(a)
b = np.array([[1,2,3],[4,5,.6]])  # create a rank 2 array
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 2])
# numpy also provides many functions to create arrays:
a = np.zeros((2,2)) # create an array of all zeros
print(a)

b = np.ones((1,2))  #create an array of all ones
print(b)

c = np.full((2,2),  7)  # create a constant array
print(c)

d = np.eye(2)  # create a 2x2 identity matrix
print(d)

e = np.random.random((2,2))  # create an array filled with random values
print(e)



ARRAY INDEXING

In [ ]:
import numpy as np
""" create the following rank 2 array with shape (3, 4)
[[1 2 3 4]
 [5 6 7 8]
 [9 10 11 12 ]]"""
 a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
""" use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2; b is the following array of shape (2, 2):
[[2 3]
 [6 7]]"""
b = a[:2, 1:3]
""" a slicing of an array is a view into the same data, so modifying it
will modify the original array."""
print(a[0, 1])
b[0, 0] = 77 # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
""" two ways of accessing the data in the middle row of the array.
 mixing integer indexing with slices yields an array of lower rank,
 while using only slices yields an array of the same rank as the
 original array:"""
row_r1 = a[1, :]  # rank 1 view of the second row of a
row_r2 = a[:, 1:2] # rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
# we can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)



In [ ]:
import numpy as np
a = np.array([[1,2], [3,4], [5,6]])
# element from the source array:
print(a[[0, 0], [1, 1]])
# equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a)

# create an array of indices
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b])
a[np.arange(4), b] +=10
print(a)



In [ ]:
import numpy as np
a = np.array([[1,2], [3,4], [5,6]])
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])
print(a[a > 2])

In [ ]:
# DATATYPES
import numpy as np
x = np.array([1, 2])
print(x.dtype)
x = np.array([1.0, 2.0])
print(x.dtype)
x = np.array([1, 2],  dtype=np.int64)
print(x.dtype)

In [ ]:
# ARRAY MATH
import numpy as np
x = np.array([[1,2], [3,4]] , dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))
print(x - y)
print(np.subtract(x, y))
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))
print(np.sqrt(x))

In [ ]:
import numpy as np
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
v = np.array([9,10])
w = np.array([11, 121])
#Inner product of vectors; both produce 219
print (v.dot (w))
print(np.dot (v, w))

In [ ]:
# Matrix/vector product; both produce the rank 1 array
# [29 67]
print (x.dot (v))
print (np.dot (x, v))
# Matrix matrix product; both produce the rank 2 array
# [[19 22]
# [43 50]]
print (x.dot (y))
print (np.dot (x, y))
# Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:
import numpy as np
np.array([[1,2], [3,4]])
print(np.sum (x))
# Compute sum of all elements; printa 10"
print (np.sum(x, axis=0))
# prints "(4 6)"
# Compute sum of each column:
print(np.sum(x, axis=1))
# Compute sum of each row:
# prints "[3 71]"

In [ ]:
import numpy as np
x = np.array([[1,2], [3,4]])
print(x)
print(x.T)
v = np.array([1,2,3])
print(v)
print(v.T)

