In [1]:
import array

In [2]:
arr=array.array('l',[2,4,6,8,10,12])

In [3]:
#print the original array
print("New created array", end="")

New created array

In [5]:
for l in range(0,5):
  print(arr[l],end="")
  print('\r')

2
4
6
8
10


In [12]:
import pandas as pd

In [16]:
#dictinory of lists
dict = {'name':["Smith","Willam","Phill","Parker"],
        'age':["28","39","34","36"]}


In [18]:
 info = pd.DataFrame(dict,index = [True, True, False, True])
print(info)

         name age
True    Smith  28
True   Willam  39
False   Phill  34
True   Parker  36


In [19]:
# accesing a datafram using .loc[] function
print(info.loc[True])


        name age
True   Smith  28
True  Willam  39
True  Parker  36


In [22]:
import numpy as np

In [28]:

arr = np.arange(16)
print("The original array is:\n",arr)
#shape array with 2 rows and 8 columns
arr = np.arange(16).reshape(2,8)
print("\nreshaped array:\n",arr)
#shape arary with 2 rows and 8 columns
arr = np.arange (16).reshape(8,2)
print("\nreshaped array:\n",arr)


The original array is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

reshaped array:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

reshaped array:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
